name: Lint and Test Check

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y black click
          pip install click==8.1.3
          pip install pipx
          pipx install black
          pip install flake8==4.0.1 flake8-bugbear==22.1.11 flake8-pie==0.15.0 isort==5.9.3 mypy==0.931 pytest==7.0.1

      - name: Run black --check
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run isort --check
        run: isort --check-only .

      - name: Run mypy
        run: mypy .

      - name: Run pytest
        run: pytest
