name: Lint and Test Check

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run black --check
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run isort --check
        run: isort --check-only .

      - name: Run mypy
        run: mypy .

      - name: Run pytest
        run: pytest
